name: End-to-End

on: [push]

jobs:
  ng-e2e:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Cache Gradle artifacts (downloaded JARs, the wrapper, and any downloaded JDKs)
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.gradle/jdks
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/.gradle/') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies (npm ci)
      run: npm ci
      working-directory: ./client

    - name: Start server and run e2e tests
      run: cd server && ./gradlew run & cd client && npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js


