name: End-to-End

on: [push]

jobs:
  ng-e2e:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Gradle artifacts (downloaded JARs, the wrapper, and any downloaded JDKs)
      uses: actions/setup-node@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Run e2e tests
      uses: cypress-io/github-action@v2
      with:
        start: ${{ github.workspace }}/server/gradlew run -p ${{ github.workspace }}/server/
        command: npm run e2e
        working-directory: ./client
